routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('sintegra')->name('sintegra.')->group(function () {
	Route::get('/search', [ 'uses' => 'SintegraController@search' ])->name('search');
	Route::get('/', ['uses' => 'SintegraController@index' ])->name('index');
	Route::delete('/{sintegra}', ['uses' => 'SintegraController@destroy'])->name('destroy');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('api/sintegra/es/{cnpj}', ['uses' => 'Admin\SintegraController@search']);

app/Sintegra.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property \Carbon\Carbon $created_at
 * @property int $id
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property array $data
 */
class Sintegra extends Model
{
	use SoftDeletes;

    protected $table = 'sintegra';

    protected $fillable = ['user_id', 'cnpj', 'data'];

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $casts = [
    	'data'  => 'array'
    ];

    public function user ()
    {
    	return $this->belongsTo(User::class);
    }

    public function toArray() {
	    return [
	    	'id'            => $this->id,
	    	'data'          => $this->data,
		    'created_at'    => $this->created_at->toAtomString()
	    ];
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sintegra ()
    {
    	return $this->hasMany(Sintegra::class);
    }
}

app/Http/Controllers/Admin/SintegraController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Services\SintegraService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class SintegraController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @param Request $request
	 * @param $cnpj
	 *
	 * @return \Illuminate\Http\Response
	 */
    public function search(Request $request, $cnpj)
    {
	    $error = $this->validateLogin($request);

    	if ( !$error ) {
    		return response()->json([
    			'data'  => [
    				'message'   => 'username or password wrong. try again'
			    ]
		    ]);
	    }

	    $crawler = app(SintegraService::class)->searchInSintegra($cnpj);

        return response()->json([
        	'data'  => $crawler
        ]);
    }

	/**
	 * @param Request $request
	 *
	 * @return bool
	 */
    private function validateLogin (Request $request)
    {
//	    if (Auth::check()) {
//	    	return true;
//	    }
//
//	    $validator = Validator::make($request->all(), [
//		    'username' => 'required|email',
//		    'password' => 'required|alphaNum|min:3',
//	    ]);
//
//	    if ( $validator->fails() ) {
//	    	return false;
//	    }

//	    if ( Auth::attempt(['email' => $request->username, 'password' => $request->password]) ) {
//	    	return true;
//	    }

	    return true;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SintegraController.php
<?php

namespace App\Http\Controllers;

use App\Sintegra;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SintegraController extends Controller
{

	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$sintegra = Sintegra::whereHas('user', function ($query) {
			$query->where('id', Auth::user()->id);
		})->latest()->paginate(5);

		return view('sintegra.index')->with(compact('sintegra'));
	}

	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search()
    {
        return view('sintegra.search');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sintegra  $sintegra
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sintegra $sintegra)
    {
	    $sintegra->delete();

        return redirect()->route('sintegra.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    <a href="{{ route('sintegra.search') }}" class="btn btn-primary">Pesquisar no Sintegra</a>
                    <a href="{{ route('sintegra.index') }}" class="btn btn-primary">Pesquisas feitas</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="api-route" content="{{ url('/') }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/sintegra/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Pesquisas feitas no Sintegra</div>

                    <div class="card-body table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th> CNPJ </th>
                                    <th> Resultado </th>
                                    <th> Data da Pesquisa </th>
                                    <th> Ação </th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($sintegra as $enterprise)
                                    <tr>
                                        <td>{{ $enterprise->cnpj }}</td>
                                        <td>
                                            <sintegra-modal-result
                                                    :sintegra="{{ json_encode($enterprise->data) }}"
                                                    :id="{{ $enterprise->id }}"
                                            ></sintegra-modal-result>
                                        </td>
                                        <td>{{ $enterprise->created_at->format('d/m/Y') }}</td>
                                        <td>
                                            <button type="button" class="btn btn-outline-danger" onclick="event.preventDefault(); document.getElementById('delete-{{ $enterprise->id }}').submit();">
                                                Deletar
                                            </button>
                                            <form id="delete-{{ $enterprise->id }}" action="{{ route('sintegra.destroy', $enterprise->id) }}" method="POST" style="display: none;">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                            </form>
                                        </td>
                                    </tr>
                                    @empty
                                        <tr>
                                            <td colspan="4">
                                                Sem Pesquisas
                                            </td>
                                        </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $sintegra->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sintegra/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Realizar uma pesquisa no Sintegra</div>

                    <div class="card-body">
                        <sintegra-search></sintegra-search>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection